// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-Tz4eWyspRPEPwaz0SvPmN1Ew7o7CWU',
    appId: '1:239544649783:web:90adb76cedc69b0c4dd7b2',
    messagingSenderId: '239544649783',
    projectId: 'flutter-todoapp-b6922',
    authDomain: 'flutter-todoapp-b6922.firebaseapp.com',
    storageBucket: 'flutter-todoapp-b6922.appspot.com',
    measurementId: 'G-ZPDW95EYV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJvrDR0iQiYpEqfH1QEz2rET5K7uwf70A',
    appId: '1:239544649783:android:9f0f0ea3f99561844dd7b2',
    messagingSenderId: '239544649783',
    projectId: 'flutter-todoapp-b6922',
    storageBucket: 'flutter-todoapp-b6922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HKgjfbRWm6KImFs76DX98jDKzUbqZGk',
    appId: '1:239544649783:ios:749d46dfcac836734dd7b2',
    messagingSenderId: '239544649783',
    projectId: 'flutter-todoapp-b6922',
    storageBucket: 'flutter-todoapp-b6922.appspot.com',
    iosClientId: '239544649783-0b1j9105ecn63rrdv3688hpjjim5kk3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1HKgjfbRWm6KImFs76DX98jDKzUbqZGk',
    appId: '1:239544649783:ios:48fc29649cfd50154dd7b2',
    messagingSenderId: '239544649783',
    projectId: 'flutter-todoapp-b6922',
    storageBucket: 'flutter-todoapp-b6922.appspot.com',
    iosClientId: '239544649783-in9v8gcn5pq0g629onqc6lm2rqmhj969.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
